#%RAML 1.0
title: Infractions Montréal
baseUri: http://127.0.0.1:5000
version: 1
# TODO : À Compléter
types:
  Utilisateur:
    type: object
    properties:
      prenom: {type: string}
      nom: {type: string}
      courriel: {type: string}
      confirmation_courriel: {type: string}
      mot_de_passe: {type: string}
      confirmation_mot_de_passe: {type: string}
      etablissements:
        type: array
        items: {type: string}
    additionalProperties: false
    example: |
      {
        "prenom": "Jeam",
        "nom": "Mathieu",
        "courriel": "jean.mathieu69@hotmail.com",
        "confirmation_courriel": "jean.mathieu69@hotmail.com",
        "mot_de_passe": "pouletGrille69!",
        "etablissements": ["Yumi Burger", "Pizza St-Laurent", "Harveys"]
      }

/api/inscription:
  post:
    description: L'utilisateur se créé un compte
    body:
      application/json:
        type: Utilisateur
    responses:
      201:
        body:
          application/json:
            example: |
              {
                "message": "L'utilisateur Aaron Osorio a été ajouté avec succès."
              }
      400:champs_manquant:
        description: Champ manquant, tous les champs doivent être remplis et respecter les critères
        body:
          application/json:
            example: |
              {
                "'mot_de_passe' is a required property"
              }
      400:mauvais type:
        description: Champ du mauvais type
        body:
          application/json:
            example: |
              {
                "12 is not of type 'string'"
              }
      500:
        description: Une erreur interne s'est produite. L'erreur a été signalée à l'équipe de développement.
        body:
          application/json:
            example: |
              {
                "error": "Une erreur interne s'est produite."
              }

types:
  Infraction:
    type: object
    properties:
      id: {type: integer}
      id_poursuite: {type: integer}
      id_businness: {type: integer}
      date: {type: string}
      description: {type: string}
      adresse: {type: string}
      date_jugement: {type: string}
      etablissement: {type: string}
      montant: {type: number}
      proprietaire: {type: string}
      ville: {type: string}
      statut: {type: string}
      date_statut: {type: string}
      categorie: {type: string}
    example: |
    {
      "id": 1,
      "id_poursuite": 1,
      "id_businness": 1,
      "date": "2022-01-01",
      "description": "Infraction XYZ",
      "adresse": "123 Rue ABC",
      "date_jugement": "2022-01-01",
      "etablissement": "Restaurant XYZ",
      "montant": 100,
      "proprietaire": "John Doe",
      "ville": "Montréal",
      "statut": "Ferme",
      "date_statut": "2022-01-01",
      "categorie": "XYZ"

    }

/api/contraventions:
  get:
    description: Récupère les contraventions pour une période donnée en paramètre
    queryParameters:
      du:
        description: Date de début de la période
        type: date
        required: true
      au:
        description: Date de fin de la période
        type: date
        required: true
    responses:
      200:
        body:
          application/json:
            type: Infraction[]
            example: |
              [
                {
                  "id": 1,
                  "id_poursuite": 1,
                  "id_businness": 1,
                  "date": "2022-01-01",
                  "description": "Infraction XYZ",
                  "adresse": "123 Rue ABC",
                  "date_jugement": "2022-01-01",
                  "etablissement": "Restaurant XYZ",
                  "montant": 100,
                  "proprietaire": "John Doe",
                  "ville": "Montréal",
                  "statut": "Ferme",
                  "date_statut": "2022-01-01",
                  "categorie": "XYZ"
                }
              ]
      400:
        description: Les dates de début et de fin de la période doivent être fournies
        body:
          application/json:
            example: |
              {
                "error": "Les dates de début et de fin de la période doivent être fournies."
              }
      404:
        description: Aucune contravention n'a été trouvée pour la période donnée
        body:
          application/json:
            example: |
              {
                "error": "Aucune contravention n'a été trouvée pour la période donnée."
              }
      500:
        description: Une erreur interne s'est produite. L'erreur a été signalée à l'équipe de développement.
        body:
          application/json:
            example: |
              {
                "error": "Une erreur interne s'est produite."
              }


types:
  Plainte:
    type: object
    properties:
      id: {type: integer}
      etablissement: {type: string}
      adresse: {type: string}
      date_visite_client: {type: string, format: date}
      nom_client: {type: string}
      prenom_client: {type: string}
      description_probleme: {type: string}
    additionalProperties: false
    example: |
      {
        "id": 1,
        "etablissement": "Restaurant XYZ",
        "adresse": "123 Rue ABC",
        "date_visite_client": "2022-01-01",
        "nom_client": "Doe",
        "prenom_client": "John",
        "description_probleme": "Problème XYZ"
      }

/api/demande-inspections:
  post:
    description: L'utilisateur envoie une plainte pour un établissement
    body:
      application/json:
        type: Plainte
    responses:
      201:
        body:
          application/json:
            example: |
              {
                "message": "La plainte pour l'établissement a été envoyée avec succès."
              }
      400:
        description: Champ manquant, tous les champs doivent être remplis et respecter les critères
        body:
          application/json:
            example: |
              {
                "error": "Le formulaire n'a pas été rempli correctement, veuillez remplir tous les champs et respecter les critères"
              }
      500:
        description: Une erreur interne s'est produite. L'erreur a été signalée à l'équipe de développement.
        body:
          application/json:
            example: |
              {
                "error": "Une erreur interne s'est produite. L'erreur a été signalée à l'équipe de développement."
              }



/api/supprimer-inspection/<int:id_inspection>:
  delete:
    description: Supprime une inspection
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "message": "L'inspection a été supprimée avec succès."
              }
      500:
        description: Une erreur interne s'est produite.
        body:
          application/json:
            example: |
              {
                "error": "Une erreur interne s'est produite. L'erreur a été signalée à l'équipe de développement."
              }


/api/supprimer-etablissement/<string:etablissement>:
  delete:
    description: Supprime un établissement
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "message": "L'établissement a été supprimé avec succès."
              }
      500:
        description: Une erreur interne s'est produite.
        body:
          application/json:
            example: |
              {
                "error": "Une erreur interne s'est produite. L'erreur a été signalée à l'équipe de développement."
              }